### ISSUE TITLE
Page Not Found in Direct

### ISSUE THREAD

**Issue by ArcherEmiya05** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#102]
Upon clicking a hyperlinked text "Direct" it throws a 404 Error "www.sample.com/admin/Direct"

**Comment by ArcherEmiya05** [comment]
Under more info in Orders navigation in Admin page

**Comment by ArcherEmiya05** [comment]
another thing is when a vendor add some item then a buyer click on Product Information 404 Page Not Found also appeared. 
![image](https://user-images.githubusercontent.com/38008900/45432391-52063900-b6dc-11e8-9c97-a1897fdb3f2a.png)

**Comment by kirilkirkov** [comment]
@ArcherEmiya05 hm, yes, "come from site" is from which site comes the buyer but if is direct traffic just must remove link.
Second but tomorrow i will check.

**Comment by kirilkirkov** [comment]
@ArcherEmiya05 First problem with Redirect link is fixed - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/1a9da060ded819590334f9403fc5a5bfcc23f4a2
The second problem maybe is because you are not set title for product in default language. All urls are generated from title in default selected language

**Comment by ArcherEmiya05** [comment]
Still I am getting the error with the "Direct" 
![image](https://user-images.githubusercontent.com/38008900/45527429-14a1c880-b80e-11e8-9f02-c56d2ba00efc.png)
