### ISSUE TITLE
Can not locate folders needed to load css and js

### ISSUE THREAD

**Issue by gxe1157** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#27]
Can not locate folders needed:

<link href="http://localhost/shop/templatecss/custom.css" rel="stylesheet">
<link href="http://localhost/shop/cssloader/theme.css" rel="stylesheet">
<script src="http://localhost/shop/loadlanguage/all.js"></script>
<script src="http://localhost/shop/templatejs/mine.js"></script>

Please advise,

**Comment by kirilkirkov** [comment]
<script src="http://localhost/shop/loadlanguage/all.js"></script> - this point to Loader controller (/application/controllers/Loader.php) jsFile method. This method search this file in /application/language/_yourlanguagename_/js/_jsfilename.js_
This file contains translations that are loaded from other javascript files.

<script src="http://localhost/shop/templatejs/mine.js"></script> -  this point to Loader controller (/application/controllers/Loader.php) templateJs method. This method loads your own javascript files from /application/views/templates/_templatename_/assets/js/_filename.js_. There you can write your own javascript code to be loaded from selected template.

If you have not changed anything by these methods, the reason why the files are not found maybe is that you host this project in directory like _http://localhost/shop_, not in - _http://localhost/_ (or virtual host) and if you host this project in directory you must change /application/config/config.php - $config['base_url'] to http://localhost/shop and your .htaccess file to:
**RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?/$1 [L]**

But you will must set this directory in css files for images because this will not load.. :)

**Example:**
.avatar {
background-image: url("/assets/imgs/login-cover.png");
}
_TO:_
.avatar {
background-image: url("/shop/assets/imgs/login-cover.png");
}
@gxe1157

**Comment by vlahx** [comment]
I tried to use the shop on Windows just for helping and I got these errors
![image](https://user-images.githubusercontent.com/19729877/31007158-3569c802-a508-11e7-806f-92757ebb0632.png)
I try to understand why. On Linux and on a domain name, subdomain works good.
I think the problem is in Loader, because the sigle function which dont work is templateCssImage, Css and js works good.
I am not sure how get this path to imgs  because it is good defined in Loader.php

**Comment by kirilkirkov** [comment]
@vlahx hmm, I test on windows 7 with XAMPP installed and in directory http://localhost/shop but i dont have this problem. Can you send me apache error logs when try to open this url?

**Comment by vlahx** [comment]
@kiril 
`[Tue Oct 03 08:25:41.032203 2017] [:error] [pid 2492:tid 1028] [client ::1:1481] PHP Fatal error:  Call to undefined function mime_content_type() in C:\\SERVER\\Apache24\\htdocs\\shop2\\application\\controllers\\Loader.php on line 103, referer: http://localhost/shop2/`
Thanks for advise, on the top is the las error from Apache, I dont use xampp or other lamps, I have installed apache, mysql and php, separately.
The problems comes from this line from loader ` $image_mime = mime_content_type($path);`
I will fix it, no mine_type activated in Apche until now :-P but I didnt look in apache logs until now to see what happens

**Comment by kirilkirkov** [comment]
@vlahx  Here is your fix - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/9e4098f5344261aaad9e1d96d394b14995a2d1c9 :) 

`        if (function_exists('mime_content_type')) {
            $image_mime = mime_content_type($path);
        } else {
            $finfo = finfo_open(FILEINFO_MIME_TYPE);
            $image_mime = finfo_file($finfo, $path);
            finfo_close($finfo);
        }`

**Comment by vlahx** [comment]
It's a good code but still don't working, I have same errors.
Work without no errors using like bellow:
`$img = file_get_contents($path);
        if (!$img) {
            header('HTTP/1.1 404 Not Found');
            return;
        }
          echo $img;`
Just eliminate $image_mime. I know it's not correct but isn't a big problem, on my linux everythings work good and load all functions from Loader.php in original code.
Thanks for your time and will be in touch, I propose to work for some developments when I will have more time, because is a good ecommerce application, I like it.

**Comment by kirilkirkov** [comment]
@vlahx Okey, greetings! :)
