### ISSUE TITLE
Templates are not working

### ISSUE THREAD

**Issue by nikhilkhot46** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#84]
There is no cssloader so there is not loading any templates for frontend.?

**Comment by Have-a-Laugh** [comment]
I can also verify this issue, after spending an hour looking into this I did notice the .htaccess file in the root directory doesn't get downloaded if I click on the "Download ZIP" button under the "Clone or Download" tab, I manually downloaded it and put it into my directory, made sure mod_rewrite was enabled but that didn't seem to make any difference either. I have verified "mod_rewrite" is displayed under the "Loaded Modules" table on the phpinfo.php file I created to check to make sure it was indeed enabled, sorry I can't be of more help @nikhilkhot46, hopefully the main developer will be able to step in and help us, :+1:

**Comment by Have-a-Laugh** [comment]
I'm also having the same issue as @nikhilkhot46

**Comment by kirilkirkov** [comment]
@nikhilkhot46 @Have-a-Laugh Check your .htaccess file is there. "cssloader" is router. Or check your permissions if you use Linux

**Comment by kirilkirkov** [comment]
All templates work.

**Comment by sammysium** [comment]
Sorry but you do enjoy closing issues without investigating and giving support, tho as a free application, I understand your frustration. The templates might work in your setup but definitly not in mine and instead of saying it is working, you can, with all do respect, give users some guidance as to what is failing.

**Comment by kirilkirkov** [comment]
@sammysium In the readme.md file clearly describes what the reason is not to load css and js files at the initial installation and how to fix that. 
The question "There is no cssloader so there is not loading any templates for frontend.?" mean that the user not read installation steps.
This application works with default web server installation. If there was something specific in web server or database it would have been described in readme.md, but dont.

When users post issues it is good to describe in detail the version of php, os, etc. so that I can help as much as possible. In the question "CSS dont work", how should I answer?

**Comment by nikhilkhot46** [comment]
![capture](https://user-images.githubusercontent.com/33891859/52110607-27833100-2627-11e9-9b30-db8fc6aaa169.PNG)

Please check above image and help  me
